import type { Metadata } from "next"
import { Geist, Sora } from "next/font/google"
import "./globals.css"
import type React from "react" // Import React

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})
const soraSans = Sora({
  variable: "--font-sora-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${soraSans.variable} antialiased h-full bg-violet-950`}
        style={{
          backgroundImage: "url('/images/6349232.jpg')",
          backgroundSize: "cover",
          backgroundPosition: "center",
          backgroundAttachment: "fixed",
          backgroundRepeat: "no-repeat",
          height: "100vh", // Lock body height to the viewport height
          overflowY: "scroll", // Enable vertical scrolling
          scrollSnapType: "y mandatory", // Enable snapping on vertical scroll
        }}
      >
        {children}
      </body>
    </html>
  )
}
